# Funding options for libmpq, ordered by priority
github: mbroemme

# Open-source dependency funding
thanks_dev: u/gh/mbroemme

# Recurring or one-time community support
liberapay: mbroemme
ko_fi: mbroemme
buy_me_a_coffee: mbroemme

# Direct donation
custom:
  - 'https://www.paypal.com/donate/?hosted_button_id=TJLZRF9BPVX22'
