.\" Copyright (c) 2021 Maik Broemme <mbroemme@libmpq.org>
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH VDI-STREAM-CLIENT 1 2021-01-26 "VDI Stream Client" "multimedia"
.SH NAME
vdi-stream-client \- a low latency desktop streaming client
.SH SYNOPSIS
.B vdi-stream-client
[\fI\-\-session\fP <id>] [\fI\-\-peer\fP <id>] [\fIoptions\fP]
.SH DESCRIPTION
.PP
VDI Stream Client is a tiny and low latency Linux client which connects
to Parsec Host running on Windows. It allows to run fully GPU accelerated
Windows desktop environment on a remote machine while streaming the
content to a local Linux system which process keyboard and mouse input.
The remote server can be a virtual machine running on-top of on-premise
deployments of Virtuozzo Hybrid Server, KVM or Xen. It can also connect
to public clouds like Amazon (EC2 G3 Accelerated) or Microsoft Azure
(NV6). It uses Simple DirectMedia Layer (SDL2) for low-level access to
audio, video, keyboard, mouse and clipboard.
.SH OPTIONS
Help options:
.TP 8
.B  \-h|\-\-help
.ti 15
Print the usage message on the standard output.
.TP 8
.B  \-v|\-\-version
.ti 15
Print the currently installed version on the standard output.
.PP
Parsec options:
.TP 8
.B  \-\-session <\fIid\fP>
.ti 15
The session ID to connect to Parsec service. This option is mandatory.
.TP 8
.B  \-\-peer <\fIid\fP>
.ti 15
The peer ID of the remote Parsec host. This option is mandatory.
.TP 8
.B  \-\-timeout <\fIseconds\fP>
.ti 15
The connection timeout when first connection to host is established.
There will be no reconnect in this case. The default timeout is 5
seconds.
.TP 8
.B  \-\-speed <\fIspeed\fP>
.ti 15
The mouse wheel snesitivity to use, supported range is between 0
(disable mouse wheel completely) up to 500. The value is in pixel. The
default value is 100.
.TP 8
.B  \-\-width <\fIwidth\fP>
.ti 15
The host screen and window width to use. The host will change
resolution either to specified value or - if not supported - to closest
one which matches. If not used, the client will resize window to current
configured host width. The value is in pixel.
.TP 8
.B  \-\-height <\fIheight\fP>
.ti 15
The host screen and window height to use. The host will change
resolution either to specified value or - if not supported - to closest
one which matches. If not used, the client will resize window to current
configured host height. The value is in pixel.
.PP
Parsec Warp options:
.TP 8
.B  \-\-no\-subsampling
.ti 15
Disable compression and chroma subsampling. If disabled, host will
compress video stream and apply chroma subsampling with mode 4:2:0 to
reduce data transfers. If enabled, no chroma subsampling is applied and
client will receive sharp and crisp stream with mode 4:4:4. Disabling is
only available under commercial subscription Parsec Warp. It is enabled
by default.
.PP
Client options:
.TP 8
.B  \-\-no\-acceleration
.ti 15
Disable hardware accelerated client decoding. If disabled, client will
decode frames in software on CPU. If enabled, client will decode frames
acclerated with the help of GPU. In both cases frames are rendered with
OpenGL. With software implementation it is almost impossible to reach
smooth client rendering. It is enabled by default.
.TP 8
.B  \-\-no\-upnp
.ti 15
Disable UPnP NAT traversal support. If disabled, client may not be
able to connect to host. If enabled, client will use UPnP to assist
NAT traversal. It is not recommended to turn it off due to UDP
client listening. It is enabled by default.
.TP 8
.B  \-\-no\-reconnect
.ti 15
Disable automatic reconnect in case of network or service failures. If
disabled, client will immediately terminate on failures. If enabled a
black window with text "Reconnecting..." is shown in case of failures.
It is recommended to leave it enabled if you are on roaming or an
unstable and slow network link. It is enabled by default.
.TP 8
.B  \-\-no\-grab
.ti 15
Disable exclusive mouse grab. If disabled, the mouse is passive grabbed
and can enter and leave the window when mouse is moved. If enabled, the
first press of any mouse button will lock the mouse into the window. To
release the mouse grab you need to press "Ctrl+Alt". If an application
requests relative mode it is being grabbed regardless of this option,
mostly the case for DirectX applications and during login of the Windows
user. Without relative grabbing most games would behave unpredictable.
A relative grabe can be released with "Ctrl+Alt". A relative grab can be
noticed in the Window title and with an invisible the mouse cursor.
.TP 8
.B  \-\-no\-screensaver
.ti 15
Disable screen saver and screen locker support on client machine (Linux
X11). If disabled, configured X11 screen saver and lockers are ignored
and X11 will never start them. This applies only to screen savers and
lockers using the X11 API. If enabled, X11 screen saver and lockers will
work as usual. It is enabled by default.
.TP 8
.B  \-\-no\-clipboard
.ti 15
Disable clipboard sharing between client and host. If disabled, the
clipboards of client and host are independent and never synchronized. It
helps to avoid occasional leaks of sensitive information made by copy
and paste mistakes. If enabled, both clipboards are always synchronized
in bi-directional mode. It is enabled by default.
.TP 8
.B  \-\-no\-audio
.ti 15
Disable audio streaming support. If disabled, no audio from host is
streamed and played on client machine. If enabled, audio is streamed
and played with default audio device used by SDL. It is enabled by
default.
.TP 8
.B  \-\-no\-hevc
.ti 15
Disable H.265 (HEVC) video codec. If disabled, client will use H.264
(AVC) video codec. If enabled, client will use H.265 (HEVC) video codec.
There is a trade-off between CPU performance and network latency and
bandwidth consumption. When using H.265 (HEVC) - even in case of GPU
decoding - CPU load and network latency is higher while network
bandwidth is reduced. When using H.264 (AVC) the CPU load and network
latency is lower while more network bandwidth is consumed. It is enabled
by default.
.PP
USB options:
.TP 8
.B  \-\-redirect <\fIvendorID\fP>:<\fIproductID\fP>@<\fIip\fP>#<\fIport\fP>,[...]
.ti 15
The USB devices to redirect to the host. The client will monitor the
specified USB device with <\fIvendorID\fP> and <\fIproductID\fP> for
hotplug events (attach and detach). To get a list of available USB devices
you can use the "lsusb" command. If a USB device is connected to the
client, it gets automatically redirected to the host with exclusive
access. The client will connect to <\fIip\fP> and <\fIport\fP> to your
virtualization host to redirect devices to the hypervisor. Multiple USB
devices can be redirected if comma separated. You can redirect up to 8
devices in total. Moreover, devices are reconnected to the host
automatically when you unplug and plug them again to the USB port and if
not connected during startup of the client, they are monitored and
redirected as soon as they are attached.
.SH KEYBOARD CONTROL
During connection to the host, you can use certain key combinations to
release keyboard grab or to switch into force grab mode.
.TP 8
.B  Ctrl+Alt
.ti 15
Toggle mouse and keyboard grab if exclusive mouse grab is enabled. If any
mouse button is pressed, the cursor will be locked into the window and all
keys are passed. The Ctrl+Alt key combination will release the grab.
See \-\-no\-grab option for more details.
.TP 8
.B  Shift+F12
.ti 15
Toggle mouse and keyboard grab regardless if exclusive grab is enabled
or disabled. If enabling forced grab, it will lock the cursor to the window
and pass all keys, except Shift+F12 to the window. The client configured
screen saver and screen locker is disabled and host must process locking.
The Ctrl+Alt key combination will not release a forced grab. If disabling
forced grab, it will release the mouse from the window, don't pass window
manager key combinations anymore and re-enable screen saver and screen
locker if necessary.
.SH AUTHOR
Written by Maik Broemme <mbroemme@libmpq.org>
.SH REPORTING BUGS
Report bugs to <https://github.com/mbroemme/vdi-stream-client/issues>
.SH COPYRIGHT
VDI Stream Client is a very tiny and low latency desktop streaming
client for remote Windows guests with GPU passthrough which supports
Nvidia NVENC, AMD VCE, VCN and Intel Quick Sync Video.

Copyright (C) 2020-2021 Maik Broemme <mbroemme@libmpq.org>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
